club_biz/config/routes.rb
ClubBiz::Application.routes.draw do  
  get "search/index"
  resources :club_requests

  devise_for :admins
  get 'admins/index' => 'admins#index', as: :admins_index
  post 'admins/accept' => 'admins#accept', as: :accept_club_request
  post 'admins/reject' => 'admins#reject', as: :reject_club_request

  devise_for :students

  resources :bookings

  resources :tickets

  resources :events
  post 'events/add_ticket' => 'events#add_ticket', as: :add_ticket
  post 'events/book_ticket' => 'events#book_ticket', as: :book_ticket
  post 'events/:id/invite' => 'events#invite', as: :invite
  post 'events/:id/submit_invite' => 'events#submit_invite', as: :submit_invite
  post 'events/:id/comment' => 'events#comment', as: :comment

  resources :clubs
  post 'clubs/subscribe' => 'clubs#subscribe', as: :subscribe
  post 'clubs/unsubscribe' => 'clubs#unsubscribe', as: :unsubscribe
  post 'clubs/create_event' => 'clubs#create_event', as: :create_event
  post 'clubs/:id/announce' => 'clubs#announce', as: :announce
  post 'clubs/:id/accept_invite' => 'clubs#accept_invite', as: :accept_invite
  post 'clubs/:id/reject_invite' => 'clubs#reject_invite', as: :reject_invite

  get "visitors/index", to:'visitors#index'
  get "students/index"
  
  root "visitors#index"

end

club_biz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClubBiz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#club-biz-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Club-biz", root_path, id: "logo", class: 'navbar-brand' %>
    </div>

    

    <div class="collapse navbar-collapse" id="club-biz-menu">
      <ul class="nav navbar-nav">
          <li><a href="#" data-toggle="modal" data-target="#aboutModal">About</a></li>
          <li><%= link_to "Clubs", clubs_path %></li>
          <li><%= link_to "Events", events_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= form_tag search_index_path, :method => 'get', class: "navbar-form navbar-left" do %>
            <%= text_field_tag :search, params[:search], class: "form-control input-sm", placeholder: "Search Club/Event" %>
            <%= button_tag(type: "submit", value: "Search", class: "btn btn-default btn-sm") do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
          <% end %>
        </li>
        <% if student_signed_in? %>
          <li><%= link_to "Account Settings", edit_student_registration_path %></li>
          <li><%= link_to "Log Out", destroy_student_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Register", new_student_registration_path %></li>
          <li><%= link_to "Sign In", new_student_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% if notice %>
<div class="alert alert-success fade in">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= notice %>
</div>
<% end %>

<% if alert %>
<div class="alert alert-danger fade in">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= alert %>
</div>
<% end %>

<div class="container-fluid">
  <%= yield %>
</div>

<!-- About Club-Biz Modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="aboutModalLabel">About Club-Biz</h4>
      </div>
      <div class="modal-body">
        Created by Brian Kang, Jason Lee, Tom Huynh © 2014
      </div>
    </div>
  </div>
</div>

</body>
</html>