club_biz/config/routes.rb
ClubBiz::Application.routes.draw do  
  get "search/index"
  resources :club_requests

  devise_for :admins
  get 'admins/index' => 'admins#index', as: :admins_index
  post 'admins/accept' => 'admins#accept', as: :accept_club_request
  post 'admins/reject' => 'admins#reject', as: :reject_club_request

  devise_for :students

  resources :bookings

  resources :tickets

  resources :events
  post 'events/add_ticket' => 'events#add_ticket', as: :add_ticket
  post 'events/book_ticket' => 'events#book_ticket', as: :book_ticket
  post 'events/:id/invite' => 'events#invite', as: :invite
  post 'events/:id/submit_invite' => 'events#submit_invite', as: :submit_invite
  post 'events/:id/comment' => 'events#comment', as: :comment

  resources :clubs
  post 'clubs/subscribe' => 'clubs#subscribe', as: :subscribe
  post 'clubs/unsubscribe' => 'clubs#unsubscribe', as: :unsubscribe
  post 'clubs/create_event' => 'clubs#create_event', as: :create_event
  post 'clubs/:id/announce' => 'clubs#announce', as: :announce
  post 'clubs/:id/accept_invite' => 'clubs#accept_invite', as: :accept_invite
  post 'clubs/:id/reject_invite' => 'clubs#reject_invite', as: :reject_invite

  get "visitors/index", to:'visitors#index'
  get "students/index"
  
  root "visitors#index"

end

club_biz/app/models/ticket.rb
# SWEN30006  Software Modelling and Design
# THE CLUB-BIZ WEB-APP
# Author: Jason Lee - 591740
#         Seunghwa Kang - 602027
#         Huynh Nguyen Minh Thong - 598093
# Start date : March 22 2014
# Finish date: May 25 2014

class Ticket < ActiveRecord::Base
	belongs_to :event
	has_many :students, through: :bookings
	has_many :bookings
end

club_biz/app/controllers/tickets_controller.rb
# SWEN30006  Software Modelling and Design
# THE CLUB-BIZ WEB-APP
# Author: Jason Lee - 591740
#         Seunghwa Kang - 602027
#         Huynh Nguyen Minh Thong - 598093
# Start date : March 22 2014
# Finish date: May 25 2014

class TicketsController < ApplicationController
before_action :set_ticket, only: [:show, :edit, :update, :destroy]

	# GET /tickets
	# GET /tickets.json
	# method to displays page contains all the tickets of a event information
	def index
		@tickets = Ticket.all
	end

	# GET /tickets/1
	# GET /tickets/1.json
	# method to show a type of ticket of a event
	def show
	end

	# GET /tickets/new
	# method to make a type of ticket of a event and display the form 
	def new
		@ticket = Ticket.new(session[:ticket_params])
	end

	# GET /tickets/1/edit
	# method to edit a specify ticket
	def edit
	end

	# POST /tickets
	# POST /tickets.json
	# method to create a type of ticket of a event and save it in the database
	def create
		session[:ticket_params] = ticket_params
		@ticket = Ticket.new(session[:ticket_params])
		@event = Event.find_by(id: session[:event_id])

		respond_to do |format|

			if !@ticket.save
				format.html { render action: 'new' }
				format.json { render json: @ticket.errors, status: :unprocessable_entity }
			end

			@event.tickets << @ticket

			session[:event_id] = nil
			session[:ticket_params] = nil

			format.html { redirect_to @event, notice: 'Ticket was successfully added.' }
		end
	end

	# PATCH/PUT /tickets/1
	# PATCH/PUT /tickets/1.json
	# method to update a type of ticket of a event
	def update
		respond_to do |format|
			if @ticket.update(ticket_params)
				format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @ticket.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /tickets/1
	# DELETE /tickets/1.json
	# method to cancel a type of ticket of a event
	def destroy
		@ticket.destroy
		respond_to do |format|
			format.html { redirect_to tickets_url }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_ticket
			@ticket = Ticket.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def ticket_params
			params.require(:ticket).permit(:name, :price, :start_date, :close_date, :msg, :max_no)
		end
end

club_biz/app/helpers/tickets_helper.rb
module TicketsHelper
end

club_biz/app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :close_date %><br>
    <%= f.date_select :close_date %>
  </div>
  <div class="field">
    <%= f.label :msg %><br>
    <%= f.text_area :msg %>
  </div>
  <div class="field">
    <%= f.label :max_no %><br>
    <%= f.number_field :max_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

club_biz/app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

club_biz/app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Start date</th>
      <th>Close date</th>
      <th>Msg</th>
      <th>Max no</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.start_date %></td>
        <td><%= ticket.close_date %></td>
        <td><%= ticket.msg %></td>
        <td><%= ticket.max_no %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

club_biz/app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', new_event_path %>

club_biz/app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @ticket.start_date %>
</p>

<p>
  <strong>Close date:</strong>
  <%= @ticket.close_date %>
</p>

<p>
  <strong>Msg:</strong>
  <%= @ticket.msg %>
</p>

<p>
  <strong>Max no:</strong>
  <%= @ticket.max_no %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>