club_biz/config/routes.rb
ClubBiz::Application.routes.draw do  
  get "search/index"
  resources :club_requests

  devise_for :admins
  get 'admins/index' => 'admins#index', as: :admins_index
  post 'admins/accept' => 'admins#accept', as: :accept_club_request
  post 'admins/reject' => 'admins#reject', as: :reject_club_request

  devise_for :students

  resources :bookings

  resources :tickets

  resources :events
  post 'events/add_ticket' => 'events#add_ticket', as: :add_ticket
  post 'events/book_ticket' => 'events#book_ticket', as: :book_ticket
  post 'events/:id/invite' => 'events#invite', as: :invite
  post 'events/:id/submit_invite' => 'events#submit_invite', as: :submit_invite
  post 'events/:id/comment' => 'events#comment', as: :comment

  resources :clubs
  post 'clubs/subscribe' => 'clubs#subscribe', as: :subscribe
  post 'clubs/unsubscribe' => 'clubs#unsubscribe', as: :unsubscribe
  post 'clubs/create_event' => 'clubs#create_event', as: :create_event
  post 'clubs/:id/announce' => 'clubs#announce', as: :announce
  post 'clubs/:id/accept_invite' => 'clubs#accept_invite', as: :accept_invite
  post 'clubs/:id/reject_invite' => 'clubs#reject_invite', as: :reject_invite

  get "visitors/index", to:'visitors#index'
  get "students/index"
  
  root "visitors#index"

end

club_biz/app/models/club.rb
# SWEN30006  Software Modelling and Design
# THE CLUB-BIZ WEB-APP
# Author: Jason Lee - 591740
#         Seunghwa Kang - 602027
#         Huynh Nguyen Minh Thong - 598093
# Start date : March 22 2014
# Finish date: May 25 2014

class Club < ActiveRecord::Base
	has_and_belongs_to_many :invited_events, class_name: "Event",join_table: "invited_clubs_events"
	has_and_belongs_to_many :accepted_events, class_name: "Event",join_table: "accepted_clubs_events"
	has_and_belongs_to_many :rejected_events, class_name: "Event",join_table: "rejected_clubs_events"
	has_many :org_events, class_name: "Event", foreign_key: "org_club_id"
	has_and_belongs_to_many :members, class_name: "Student", join_table: "clubs_members"
	has_and_belongs_to_many :subscribers, class_name: "Student", join_table: "clubs_subscribers"
	belongs_to :admin, class_name: "Student"
	has_many :announcements
	
	# accepted events + organising events
	def participating_events
		events = Array.new
		events << self.accepted_events
		events << self.org_events
		return events.flatten
	end

	# method to search the record based on a search term
	def self.search(search)
  		if search
    		find(:all, :conditions => ['name LIKE ? or description LIKE ? or contact LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
  		else
    		find(:all)
  		end
	end
end

club_biz/app/controllers/clubs_controller.rb
# SWEN30006  Software Modelling and Design
# THE CLUB-BIZ WEB-APP
# Author: Jason Lee - 591740
#         Seunghwa Kang - 602027
#         Huynh Nguyen Minh Thong - 598093
# Start date : March 22 2014
# Finish date: May 25 2014

class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy, :accept_invite, :reject_invite]

  # GET /clubs
  # GET /clubs.json
  # method to displays all the clubs
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  # method to show a specify club
  def show
    @club = Club.find(params[:id])
    @participating_events = @club.participating_events
    @announcements = @club.announcements
  end

  # GET /clubs/new
  # method to initialize a form to create a new club 
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  # method to edit a specify club
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  # method to create a club and save it in the database
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @club }
      else
        format.html { render action: 'new' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  # method to update a club
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  # method to cancel a club
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end

  # method to subcribe a club by a student
  def subscribe
    @club = Club.find(params[:club_id])
    begin
      current_student.subscribed_clubs.find(params[:club_id])
    rescue Exception => e
      if student_signed_in?
        if current_student.subscribed_clubs << @club
          redirect_to @club, notice: 'You have successfully subscribed to this club.'
        else
          redirect_to @club, notice: 'Subscription was unsuccessful. Please try again later.'
        end
      else
          redirect_to @club, notice: 'You have to sign in to subscribe'
      end

    else
      redirect_to @club, notice: 'You are already subscribed to this club.'
    end
  end

  # method to unsubcribe a club by a student
  def unsubscribe
    begin
      @club = current_student.subscribed_clubs.find(params[:club_id])    
    rescue Exception => e
      @tmp = Club.find(params[:club_id])
      redirect_to @tmp, notice: 'You are not subscribed to this club.'
    else
      @tmp = @club
      if current_student.subscribed_clubs.delete(@club)
        redirect_to @tmp, notice: 'You have successfully unsubscribed to this club.'
      else
        redirect_to @tmp, notice: 'Unsubscription was unsuccessful. Please try again later.'
      end
    end
  end

  # method to initialize a form to create a event
  def create_event
    session[:club_id] = params[:club_id]
    redirect_to new_event_path
  end

  # method to post announcement to clubs members by club admin
  def announce
    @announcement = Announcement.new(content: params[:announcement][:content])
    @club = Club.find_by(id: params[:id])

    respond_to do |format|
      if @announcement.content!='' && @announcement.save
        format.html { redirect_to @club, notice: 'Announcement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @announcement }
        @club.announcements << @announcement
      else
        format.html { redirect_to @club, notice: 'Announcement was not created.' }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end

  end

  # method to accept invitation for a event by club admin
  def accept_invite
    @event = Event.find_by(id: params[:event_id])
    @club.accepted_events << @event
    @club.invited_events.delete(@event)
    @event.invited_clubs.delete(@club)

    redirect_to @club, notice: 'Invitation successfully accepted.'
  end

  # method to reject invitation for a event by club admin
  def reject_invite
    @event = Event.find_by(id: params[:event_id])
    @club.rejected_events << @event
    @club.invited_events.delete(@event)
    @event.invited_clubs.delete(@club)

    redirect_to @club, notice: 'Invitation successfully rejected.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      begin
        @club = Club.find(params[:id])
      rescue Exception => e
        render file: 'public/404', status: 404, formats: [:html]
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :description, :contact)
    end
end

club_biz/app/helpers/clubs_helper.rb
module ClubsHelper
end

club_biz/app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <br/>Note: Please enter FULL NAME. NO ABBREVIATION.<br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :contact %><br/>
    <%= f.text_area :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

club_biz/app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @club %>

club_biz/app/views/clubs/index.html.erb
<div class="col-md-10 col-md-offset-1">
<h1>Listing clubs</h1>
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Contact</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= link_to club.name, club %></td>
        <td><%= club.description %></td>
        <td><%= club.contact %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

club_biz/app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

club_biz/app/views/clubs/show.html.erb
<div class="page-header">
  <h1><%= @club.name %></h1>
</div>

<div class="row">
  <div class="col-md-2" align="center">
    <% if current_student %>
      <% if current_student.admin_club.include?(@club) %>
        <%= link_to 'ADMIN Options', "#admin-options", class: "btn btn-primary" %>

      <% else %>
        <% if not current_student.subscribed_clubs.include?(@club) %>
          <%= button_to 'Subscribe', {action: 'subscribe', :club_id => @club.id}, class: "btn btn-info" %>

        <% else %>
          <%= button_to 'Unsubscribe', {action: 'unsubscribe', :club_id => @club.id}, class: "btn btn-warning" %>
        <% end %>
      <% end %>

    <% else %>
      <%= button_to 'Sign in to Subscribe', {action: 'subscribe', :club_id => @club.id}, class: "btn btn-info", disabled: "disabled" %>
    <% end %>
  </div>

  <div class="col-md-10">
    <div class="panel panel-success">
    <div class="panel-heading">
      <ul class="nav nav-pills">
        <li class="active"><a href="#about" data-toggle="tab">About Club</a></li>
        <li><a href="#contact" data-toggle="tab">Contacts</a></li>
      </ul>
    </div>
    <div class="panel-body">
      

      <div class="tab-content">
        <div class="tab-pane active" id="about"><%= simple_format @club.description %></div>
        <div class="tab-pane" id="contact"><%= simple_format @club.contact %></div>
      </div>
    </div>
    </div>
  </div>
</div>

<hr/>

<div class="row">
  <div class="col-md-4 col-md-offset-2">
    <div class="panel panel-primary">
    <div class="panel-heading">Club Announcements</div>
    <div class="panel-body">
      <% if not @announcements.empty? %>
        <table>
          <tbody>
            <% @announcements.each do |announcement| %>
            <tr>
            <td><strong><%= link_to announcement.club.name, announcement.club %></strong>:<%= announcement.content %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        There is no announcement.
      <% end %>
    </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-primary">
    <div class="panel-heading">Club Events</div>
    <div class="panel-body">    
      <% if not @participating_events.empty? %>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Date</th>
              <th>Time</th>
              <th>Location</th>
              <th>Organising Club</th>
            </tr>
          </thead>

          <tbody>
          <% @participating_events.each do |p_event| %>
            <tr>
              <td><%= link_to p_event.name, p_event %></td>
              <td><%= p_event.date %></td>
              <td><%= p_event.time.to_s(:time) %></td>
              <td><%= p_event.location %></td>
              <td><%= p_event.org_club.name %></td>
            </tr>
          <% end %>
          </tbody>
        </table>

      <% else %>
        This club is so boring. No events at all...
      <% end %>
    </div>
    </div>
  </div>
</div>



<% if current_student and current_student.admin_club.include?(@club) %>
<div class="well" id="admin-options">
<p>
  <%= button_to 'ADMIN: Create Event', {action: 'create_event'} , :club_id => @club.id, class: "btn btn-success" %><br/>

  <strong>ADMIN: Create New Announcement</strong><br/>
  
  <%= form_for :announcement, :url => announce_path, :method => 'post' do |f| %>
    <div class="field" style="float:left;">
      <%= f.text_field :content , :size=>75%>
    </div>

    <div class="actions" style="float:left;">
      <%= f.submit 'Post'%>
    </div>

    <div style="clear:both;">
    </div>
  <% end %>

  <br/>

  <strong>ADMIN: Event Invitations</strong>
  <% if not @club.invited_events.empty? %>
  <table>
      <col width="250">
      <col width="100">
      <col width="200">
      <col width="250">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Time</th>
          <th>Location</th>
        </tr>
      </thead>

      <tbody>
        <% @club.invited_events.each do |event| %>
        <tr>
          <td><%= link_to event.name, event %></td>
          <td><%= event.date %></td>
          <td><%= event.time.to_s(:time) %></td>
          <td><%= event.location %></td>
          <td><%= button_to 'Accept', {action: 'accept_invite', :event_id => event.id}, class: "btn btn-success" %>
          <td><%= button_to 'Reject', {action: 'reject_invite', :event_id => event.id}, class: "btn btn-danger" %>
        </tr>
        <% end %>
      </tbody>
  </table>
  <% else %>
  <br/>Other clubs don't like you. No event invitation from other clubs.
  <% end %>
</p>

<hr/>

<%= link_to 'ADMIN: Edit Profile', edit_club_path(@club) %>

<hr/>
</div>
<% end %>