club_biz/config/routes.rb
ClubBiz::Application.routes.draw do  
  get "search/index"
  resources :club_requests

  devise_for :admins
  get 'admins/index' => 'admins#index', as: :admins_index
  post 'admins/accept' => 'admins#accept', as: :accept_club_request
  post 'admins/reject' => 'admins#reject', as: :reject_club_request

  devise_for :students

  resources :bookings

  resources :tickets

  resources :events
  post 'events/add_ticket' => 'events#add_ticket', as: :add_ticket
  post 'events/book_ticket' => 'events#book_ticket', as: :book_ticket
  post 'events/:id/invite' => 'events#invite', as: :invite
  post 'events/:id/submit_invite' => 'events#submit_invite', as: :submit_invite
  post 'events/:id/comment' => 'events#comment', as: :comment

  resources :clubs
  post 'clubs/subscribe' => 'clubs#subscribe', as: :subscribe
  post 'clubs/unsubscribe' => 'clubs#unsubscribe', as: :unsubscribe
  post 'clubs/create_event' => 'clubs#create_event', as: :create_event
  post 'clubs/:id/announce' => 'clubs#announce', as: :announce
  post 'clubs/:id/accept_invite' => 'clubs#accept_invite', as: :accept_invite
  post 'clubs/:id/reject_invite' => 'clubs#reject_invite', as: :reject_invite

  get "visitors/index", to:'visitors#index'
  get "students/index"
  
  root "visitors#index"

end

club_biz/app/models/event.rb
# SWEN30006  Software Modelling and Design
# THE CLUB-BIZ WEB-APP
# Author: Jason Lee - 591740
#         Seunghwa Kang - 602027
#         Huynh Nguyen Minh Thong - 598093
# Start date : March 22 2014
# Finish date: May 25 2014

class Event < ActiveRecord::Base
	has_many :tickets
	has_and_belongs_to_many :accepted_clubs, class_name: "Club",join_table: "accepted_clubs_events"
	has_and_belongs_to_many :rejected_clubs, class_name: "Club",join_table: "rejected_clubs_events"
	has_and_belongs_to_many :invited_clubs, class_name: "Club",join_table: "invited_clubs_events"
	belongs_to :org_club, class_name: "Club"
	has_many :comments

	# method to return a array of admins belong to a club which organize a event
	def admins
		admins_array = Array.new
		admins_array << self.org_club.admin
		self.accepted_clubs.each do |club|
			admins_array << club.admin
		end
		return admins_array.flatten
	end

	# method to return a array of members belong to a club which organize a event
	def members
		members_array = Array.new
		members_array << self.org_club.members
		self.accepted_clubs.each do |club|
			members_array << club.members
		end
		return members_array.flatten
	end

	def bookings
		@bookings = Array.new
		self.tickets.each do |ticket|
      		if Booking.where(ticket_id: ticket.id).any?
        		@bookings << Booking.where(ticket_id: ticket.id)
      		end
    	end
    	return @bookings
    end

    def num_booked_tickets
    	@booked_tickets = 0

    	if !self.bookings.empty?
	    	self.bookings.each do |relation|
	    		relation.each do |booking|
	    			@booked_tickets += booking.num_tickets
	    		end
	    	end
	    end
	    return @booked_tickets
	end

	def revenue
    	@revenue = 0

    	if !self.bookings.empty?
	    	self.bookings.each do |relation|
	    		relation.each do |booking|
	    			@revenue += booking.ticket.price * booking.num_tickets
	    		end
	    	end
	    end
	    return @revenue
	end

	def can_invite_clubs?
		return  if @event.org_club != club && !@event.invited_clubs.include?(club) && 
		!@event.accepted_clubs.include?(club) && !@event.rejected_clubs.include?(club)
	end

	# method to search the record based on a search term
	def self.search(search)
  		if search
    		find(:all, :conditions => ['name LIKE ? or description LIKE ? or location LIKE ? or date LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
  		else
    		find(:all)
  		end
	end

end

club_biz/app/controllers/events_controller.rb
# SWEN30006  Software Modelling and Design
# THE CLUB-BIZ WEB-APP
# Author: Jason Lee - 591740
#         Seunghwa Kang - 602027
#         Huynh Nguyen Minh Thong - 598093
# Start date : March 22 2014
# Finish date: May 25 2014

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :comment]

  # GET /events
  # GET /events.json
  # method to displays all the events
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  # method to show a specify event
  def show
    @total_tickets=0
    @total_revenue=0
    @ticket = Ticket.where(event_id: params[:id])
    @booking_records= Array.new

    @booking_records = @event.bookings
    @total_tickets = @event.num_booked_tickets
    @total_revenue = @event.revenue

    @comments = Comment.where(event_id: @event.id)

    @comments = @comments.sort_by{:created_at}.reverse
  end

  # GET /events/new
  # method to initialize a form to create a new event
  def new
    @event = Event.new(session[:event_params])
  end

  # GET /events/1/edit
  # method to edit a specify event
  def edit
  end

  # POST /events
  # POST /events.json
  # method to create a event and save it in the database
  def create
    @event = Event.new(event_params)
    @club = Club.find_by(id: session[:club_id])

    respond_to do |format|
      if !@event.save
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    
      @club.org_events << @event

      session[:club_id] = nil

      format.html { redirect_to @event, notice: 'Event was successfully created.' }
      format.json { render action: 'show', status: :created, location: @event }
    end

  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  # method to update a event
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  # method to cancel a bookings
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  # POST 'events/add_ticket'
  # method to initialize to add a new type of ticket to a event
  def add_ticket
    session[:event_id] = params[:event_id]
    redirect_to new_ticket_path
  end

  # POST 'events/book_ticket'
  # method to initialize to book a type of ticket to a event
  def book_ticket
    session[:event_id] = params[:event_id]
    redirect_to new_booking_path
  end

  # POST 'events/:id/invite
  # method to initialize a invite form to invite other clubs to a event
  def invite
    @all_clubs = Club.all
    @event = Event.find_by(id: params[:event_id])
  end

  # POST 'events/:id/submit_invite'
  # method to send invite to invite other clubs to a event
  def submit_invite
    @event = Event.find_by(id: params[:id])
    @club_ids = params[:club_ids]
    
    respond_to do |format|
      @club_ids.each do |club_id|
        @invite_club = Club.find_by(id: club_id)
        @event.invited_clubs << @invite_club
      end

      format.html { redirect_to @event, notice: 'Invitation successful' }
      format.json { render action: 'show', status: :created, location: @event }
    end
  end

  # POST 'events/:id/comment'
  # method to comment on a event
  def comment
    if !student_signed_in?
        redirect_to event_path, notice: 'You must log in to comment'
    else
    @comment = Comment.new(content: params[:comment][:content])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @event, notice: 'Your comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }

        current_student.comments << @comment
        @event.comments << @comment
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :time, :description, :location)
    end
end

club_biz/app/helpers/events_helper.rb
module EventsHelper
end

club_biz/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

club_biz/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

club_biz/app/views/events/index.html.erb
<div class="col-md-10 col-md-offset-1">
<h1>All upcoming events</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Time</th>
      <th>Description</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event  %></td>
        <td><%= event.date %></td>
        <td><%= event.time.to_s(:time) %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>

      </tr>
    <% end %>
  </tbody>
</table>

</div>

club_biz/app/views/events/invite.html.erb
<h1> Invitation </h1>

<%= form_for @event, :url => submit_invite_path, :method => 'post' do |f|%>
	<ul>
		<% @all_clubs.each do |club| %>
				<% if @event.org_club != club && !@event.invited_clubs.include?(club) && !@event.accepted_clubs.include?(club) && !@event.rejected_clubs.include?(club) %>
				<li>
					<%= check_box_tag 'club_ids[]', club.id %>
					<%= club.name %>
				</li>
				<% end %>
			
		<% end %>
	</ul>

	<%= link_to 'Back', @event %>
	<div class="actions">
    	<%= f.submit 'Submit'%>
  	</div>
<% end %>

club_biz/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

club_biz/app/views/events/show.html.erb
  <p id="notice"><%= notice %></p>

  <div class="page-header">
    <% if @event.admins.include?(current_student) %>
    <div class="pull-right">
      <%= link_to 'Edit event details', edit_event_path(@event), class: "btn btn-info" %><br/><br/>
      <%= button_to 'Invite other clubs', {action: 'invite' , :event_id => @event.id}, class: "btn btn-info" %>
    </div>
    <%end%>

    <h2><%= @event.name %></h2>
    <h4><%= link_to @event.org_club.name, @event.org_club %></h4>
   
    <% @event.accepted_clubs.each do |club| %>
      <small><%= link_to club.name, club %> &nbsp </small>
    <% end %>
    <br/>
    <% if @event.admins.include?(current_student) %>

    <ul class="nav nav-pills">
      <li class="active">
        <a href='#profile' data-toggle='tab'>Event Profile</a>
      </li>
      
      <li>
        <a href='#manage' data-toggle='tab'>Manage</a>
      </li>      
    </ul>
    <%end%>  
  </div>

  <div class="tab-content">
    <div class="tab-pane active" id="profile">
  <div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <div class="panel panel-primary">
        <div class="panel-body">
          <strong>Date:</strong>
            <%= @event.date %><br/>
          <strong>Time:</strong>
            <%= @event.time.to_s(:time) %><br/>
          <strong>Location:</strong>
            <%= @event.location %><br/>
        </div>
      </div>

      <%= button_to 'Book Ticket', {action: 'book_ticket' , :event_id => @event.id}, class: "btn btn-success btn-lg" %>
    </div>

    <div class="col-md-10">
      <div class="panel panel-primary">
        <div class="panel panel-heading"><h3 class="panel-title">Description</h3></div>
        <div class="panel-body">
          <%= @event.description %>
        </div>
      </div>

      <h3>Comments</h3>
      <%= form_for :comment, :url => comment_path, :method => 'post' do |f| %>
        <div class="input-group" style="float:left;">
          <%= f.text_field :content , {placeholder: "Comment Here!", class: "form-control"}%>
          <span class="input-group-btn">
            <div class="actions" style="float:left;">
              <%= f.submit 'Post', {class: "btn btn-default"} %>
            </div>
          </span>
        </div>
        
      <% end %>
      <br/><br/><br/>

      <div class="well well-md">
      <% @comments.each do |comment| %>
        
          <strong><%= comment.student.full_name%></strong>:
          <%= comment.content %> <br/><br/>
      <% end %>
      </div>
    </div>
  </div>
  </div>
  </div>

    <div class="tab-pane" id="manage">

  <div class="row">

    <div class="col-md-2">
      <div class="panel panel-primary">
        <div class="panel-body">
          <ul>
            <li> Total tickets: <%= @total_tickets %> </li>
            <li> Total revenue: <%= @total_revenue %> </li>
          </ul>
        </div>
      </div>

        <%= button_to 'Add Ticket', {action: 'add_ticket' , :event_id => @event.id}, class: "btn btn-info" %><br/>
    </div>

    <div class="col-md-10">
      <div class="panel panel-primary">
        <div class="panel panel-heading"><h3 class="panel-title">Purchase List</h3></div>
          <table class="table">
          <thead>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Number of Tickets</th>
              <th>Ticket Type</th>
              <th>Ticket Price</th>
              <th>Purchased Date</th>
            </tr>
          </thead>

          <tbody>
          <% @booking_records.each do |relation| %>
            <% relation.each do |booking| %>
              <tr>
                <td><%= booking.student.first_name %></td>
                <td><%= booking.student.last_name %></td>
                <td><%= booking.num_tickets %></td>

                <td><%= booking.ticket.name %></td>
                <td><%= booking.ticket.price %></td>

                <td><%= booking.created_at.to_s(:short) %></td> 
              </tr>
            <% end %>
          <% end %>

          </tbody>
          </table>
        </div>
      </div>
    </div>


  </div>
  </div>